USE ArtistInfo;
ALTER TABLE Artist
ADD CONSTRAINT FK_Manager FOREIGN KEY(ManagerID) REFERENCES Manager(ManagerID)
ON UPDATE CASCADE
GO
ALTER TABLE Artist
ADD CONSTRAINT FK_Genre FOREIGN KEY(GenreID) REFERENCES Genre(GenreID)
ON UPDATE CASCADE
GO
ALTER TABLE Artist
ADD CONSTRAINT FK_Producer FOREIGN KEY(ProducerID) REFERENCES Producer(ProducerID)
ON UPDATE CASCADE
GO
ALTER TABLE Artist
ADD CONSTRAINT FK_Engineer FOREIGN KEY(EngineerID) REFERENCES LiveEngineer(EngineerID)
ON UPDATE CASCADE
GO
ALTER TABLE BandMember
ADD CONSTRAINT FK_Artist FOREIGN KEY(ArtistID) REFERENCES Artist(ArtistID)
ON UPDATE CASCADE
GO
ALTER TABLE Producer
ADD CONSTRAINT FK_GenreTable FOREIGN KEY(GenreID) REFERENCES Genre(GenreID)
ON UPDATE NO ACTION
GO
